trigger:
  branches:
    include:
      - main  # A branch que você deseja monitorar

pool:
  vmImage: 'ubuntu-latest'  # Usando uma imagem Ubuntu para rodar a build

steps:
  # Etapa para construir o projeto com Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'  # Caminho para o seu arquivo pom.xml
      goals: 'clean package'   # Comandos Maven para limpar e empacotar a aplicação
      options: '-Xmx3072m'     # Configuração de memória para o Maven
      javaHomeOption: 'JDKVersion'  # Define a versão do JDK
      jdkVersionOption: '1.11'      # Versão do JDK (11, 1.11, etc.)
      jdkArchitectureOption: 'x64'  # Arquitetura JDK
      publishJUnitResults: true     # Publica resultados de testes JUnit
      testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Localização dos relatórios de teste

  # Etapa para fazer o deploy no Azure App Service
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'conectapro-connection'  # Nome da sua Service Connection do Azure (configure no DevOps) 
      appName: 'conectapro-api'  # Nome do seu App Service (no portal do Azure)
      package: '$(System.DefaultWorkingDirectory)/target/*.jar'  # Caminho para o arquivo JAR gerado
      deploymentMethod: 'auto'  # Método de deploy automático
